pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                success {
                    junit 'jspwiki-war/target/surefire-reports/*.xml'
                }
            }
        }
        stage('SCA') {
            steps {
                dependencyCheckAnalyzer datadir: '/home/hirosh7/OWASP_NVD_Updates', hintsFile: '',
                includeCsvReports: false, includeHtmlReports: true, includeJsonReports: false,
                includeVulnReports: false, isAutoupdateDisabled: true, outdir: '.', scanpath: '.',
                skipOnScmChange: false, skipOnUpstreamChange: false, suppressionFile: '', zipExtensions: ''
            }
            post {
               always {
                    dependencyCheckPublisher canComputeNew: false, defaultEncoding: '', healthy: '',
                    pattern: '**/dependency-check-report.xml', unHealthy: ''
               }
           }
        }
        stage('SAST') {
            steps {
                sh 'mvn findbugs:findbugs'
                findbugs canComputeNew: false, defaultEncoding: '', excludePattern: '', healthy: '',
                includePattern: '', isRankActivated: true, pattern: '**/findbugsXml.xml', unHealthy: ''
            }
        }
    }
}
